(ns vwowrla.core.matchers.damage-reflected-test
  (:import
    (java.util TimeZone))
  (:use
    clojure.test
    vwowrla.core.matchers.matchers-test-utils)
  (:require
    [vwowrla.core.parser :refer [parse-line]]
    [vwowrla.core.preparsing :refer [parse-log-timestamp]]
    [vwowrla.core.events.matchers :refer [regex-matchers]]))

(def options {:log-owner-char-name "Blasticus"
              :year                2015
              :timezone            (TimeZone/getDefault)
              :windows?            false})

(def owner-char-name (:log-owner-char-name options))
(def year (:year options))
(def timezone (:timezone options))

(deftest target-reflects-elemental-damage
  (is (valid-matcher? (get-matcher regex-matchers :target-reflects-elemental-damage)))

  (is (= (parse-line "5/25 21:13:30.482  Futilian reflects 16 Fire damage to Onyxia." options)
         {:id          :target-reflects-elemental-damage
          :logfmt      :target-reflects-elemental-damage
          :event       :damage-reflected
          :line        "5/25 21:13:30.482  Futilian reflects 16 Fire damage to Onyxia."
          :timestamp   (parse-log-timestamp "5/25 21:13:30.482" options)
          :target-name "Onyxia"
          :source-name "Futilian"
          :damage      16
          :damage-type :fire}))

  (is (= (parse-line "5/25 23:26:09.552  Son of Flame reflects 50 Fire damage to Deadasfuk." options)
         {:id          :target-reflects-elemental-damage
          :logfmt      :target-reflects-elemental-damage
          :event       :damage-reflected
          :line        "5/25 23:26:09.552  Son of Flame reflects 50 Fire damage to Deadasfuk."
          :timestamp   (parse-log-timestamp "5/25 23:26:09.552" options)
          :target-name "Deadasfuk"
          :source-name "Son of Flame"
          :damage      50
          :damage-type :fire}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  You reflect 42 Fire damage to Winna's Kitten." options)
         {:id          :target-reflects-elemental-damage
          :logfmt      :target-reflects-elemental-damage
          :event       :damage-reflected
          :line        "1/2 3:45:00.123  You reflect 42 Fire damage to Winna's Kitten."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name "Winna's Kitten"
          :source-name owner-char-name
          :damage      42
          :damage-type :fire})))
