(ns vwowrla.core.matchers.dot-damages-target-test
  (:import
    (java.util TimeZone))
  (:use
    clojure.test
    vwowrla.core.matchers.matchers-test-utils)
  (:require
    [vwowrla.core.parser :refer [parse-line]]
    [vwowrla.core.preparsing :refer [parse-log-timestamp]]
    [vwowrla.core.events.matchers :refer [regex-matchers]]))

(def options {:log-owner-char-name "Blasticus"
              :year                2015
              :timezone            (TimeZone/getDefault)
              :windows?            false})

(def owner-char-name (:log-owner-char-name options))
(def year (:year options))
(def timezone (:timezone options))

(deftest dot-damages-target
  (is (valid-matcher? (get-matcher regex-matchers :dot-damages-target)))

  (is (= (parse-line "5/25 21:16:56.786  Onyxia suffers 261 Shadow damage from Smooth's Corruption." options)
         {:id          :dot-damages-target
          :logfmt      :dot-damages-target
          :event       :dot-damages-target
          :line        "5/25 21:16:56.786  Onyxia suffers 261 Shadow damage from Smooth's Corruption."
          :timestamp   (parse-log-timestamp "5/25 21:16:56.786" options)
          :target-name "Onyxia"
          :source-name "Smooth"
          :skill       "Corruption"
          :damage      261
          :damage-type :shadow
          :absorbed    nil
          :resisted    nil}))

  (is (= (parse-line "5/25 22:01:54.974  You suffer 1010 Fire damage from Gehennas's Rain of Fire. (60 absorbed)" options)
         {:id          :dot-damages-target
          :logfmt      :dot-damages-target
          :event       :dot-damages-target
          :line        "5/25 22:01:54.974  You suffer 1010 Fire damage from Gehennas's Rain of Fire. (60 absorbed)"
          :timestamp   (parse-log-timestamp "5/25 22:01:54.974" options)
          :target-name owner-char-name
          :source-name "Gehennas"
          :skill       "Rain of Fire"
          :damage      1010
          :damage-type :fire
          :absorbed    60
          :resisted    nil}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  Onyxia suffers 1337 Shadow damage from Sri'skulk's Arugal's Curse." options)
         {:id          :dot-damages-target
          :logfmt      :dot-damages-target
          :event       :dot-damages-target
          :line        "1/2 3:45:00.123  Onyxia suffers 1337 Shadow damage from Sri'skulk's Arugal's Curse."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name "Onyxia"
          :source-name "Sri'skulk"
          :skill       "Arugal's Curse"
          :damage      1337
          :damage-type :shadow
          :absorbed    nil
          :resisted    nil}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  Onyxia suffers 1337 Shadow damage from Sri'skulk's Corruption." options)
         {:id          :dot-damages-target
          :logfmt      :dot-damages-target
          :event       :dot-damages-target
          :line        "1/2 3:45:00.123  Onyxia suffers 1337 Shadow damage from Sri'skulk's Corruption."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name "Onyxia"
          :source-name "Sri'skulk"
          :skill       "Corruption"
          :damage      1337
          :damage-type :shadow
          :absorbed    nil
          :resisted    nil})))

(deftest dot-damages-target-self
  (is (valid-matcher? (get-matcher regex-matchers :dot-damages-target-self)))

  (is (= (parse-line "5/25 21:15:18.909  Onyxian Whelp suffers 179 Frost damage from your Blizzard." options)
         {:id          :dot-damages-target-self
          :logfmt      :dot-damages-target
          :event       :dot-damages-target
          :line        "5/25 21:15:18.909  Onyxian Whelp suffers 179 Frost damage from your Blizzard."
          :timestamp   (parse-log-timestamp "5/25 21:15:18.909" options)
          :target-name "Onyxian Whelp"
          :source-name owner-char-name
          :skill       "Blizzard"
          :damage      179
          :damage-type :frost
          :absorbed    nil
          :resisted    nil})))
