(ns vwowrla.core.matchers.other-damage-test
  (:import
    (java.util TimeZone))
  (:use
    clojure.test
    vwowrla.core.matchers.matchers-test-utils)
  (:require
    [vwowrla.core.parser :refer [parse-line]]
    [vwowrla.core.preparsing :refer [parse-log-timestamp]]
    [vwowrla.core.matchers :refer [regex-matchers]]))

(def options {:log-owner-char-name "Blasticus"
              :year                2015
              :timezone            (TimeZone/getDefault)
              :windows?            false})

(def owner-char-name (:log-owner-char-name options))
(def year (:year options))
(def timezone (:timezone options))

(deftest environmental-damage
  (is (valid-matcher? (get-matcher regex-matchers :environmental-damage)))

  (is (= (parse-line "5/25 23:08:30.798  Hsaru suffers 713 points of fire damage." options)
         {:id          :environmental-damage
          :logfmt      :environmental-damage
          :event       :other-damage
          :line        "5/25 23:08:30.798  Hsaru suffers 713 points of fire damage."
          :timestamp   (parse-log-timestamp "5/25 23:08:30.798" options)
          :target-name "Hsaru"
          :damage      713
          :damage-type :fire
          :absorbed    nil
          :resisted    nil}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  You suffer 42 points of fire damage." options)
         {:id          :environmental-damage
          :logfmt      :environmental-damage
          :event       :other-damage
          :line        "1/2 3:45:00.123  You suffer 42 points of fire damage."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name owner-char-name
          :damage      42
          :damage-type :fire
          :absorbed    nil
          :resisted    nil})))

(deftest lava-swim-damage
  (is (valid-matcher? (get-matcher regex-matchers :lava-swim-damage)))

  (is (= (parse-line "5/25 21:58:13.460  Agusto loses 583 health for swimming in lava." options)
         {:id          :lava-swim-damage
          :logfmt      :lava-swim-damage
          :event       :other-damage
          :line        "5/25 21:58:13.460  Agusto loses 583 health for swimming in lava."
          :timestamp   (parse-log-timestamp "5/25 21:58:13.460" options)
          :target-name "Agusto"
          :source      "Swimming in lava"
          :damage      583
          :damage-type :fire
          :absorbed    nil
          :resisted    nil}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  You lose 42 health for swimming in lava." options)
         {:id          :lava-swim-damage
          :logfmt      :lava-swim-damage
          :event       :other-damage
          :line        "1/2 3:45:00.123  You lose 42 health for swimming in lava."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name owner-char-name
          :source      "Swimming in lava"
          :damage      42
          :damage-type :fire
          :absorbed    nil
          :resisted    nil}))

  (is (= (parse-line "5/25 23:16:47.108  Agusto loses 0 health for swimming in lava. (632 absorbed)" options)
         {:id          :lava-swim-damage
          :logfmt      :lava-swim-damage
          :event       :other-damage
          :line        "5/25 23:16:47.108  Agusto loses 0 health for swimming in lava. (632 absorbed)"
          :timestamp   (parse-log-timestamp "5/25 23:16:47.108" options)
          :target-name "Agusto"
          :source      "Swimming in lava"
          :damage      0
          :damage-type :fire
          :absorbed    632
          :resisted    nil}))

  (is (= (parse-line "6/9 21:32:31.616  Hsaru loses 205 health for swimming in lava. (380 absorbed)" options)
         {:id          :lava-swim-damage
          :logfmt      :lava-swim-damage
          :event       :other-damage
          :line        "6/9 21:32:31.616  Hsaru loses 205 health for swimming in lava. (380 absorbed)"
          :timestamp   (parse-log-timestamp "6/9 21:32:31.616" options)
          :target-name "Hsaru"
          :source      "Swimming in lava"
          :damage      205
          :damage-type :fire
          :absorbed    380
          :resisted    nil})))

(deftest fall-damage
  (is (valid-matcher? (get-matcher regex-matchers :fall-damage)))

  (is (= (parse-line "5/25 23:11:05.498  Crowquill falls and loses 167 health." options)
         {:id          :fall-damage
          :logfmt      :fall-damage
          :event       :other-damage
          :line        "5/25 23:11:05.498  Crowquill falls and loses 167 health."
          :timestamp   (parse-log-timestamp "5/25 23:11:05.498" options)
          :target-name "Crowquill"
          :source      "Falling"
          :damage      167}))

  (is (= (parse-line "5/25 23:10:40.994  You fall and lose 939 health." options)
         {:id          :fall-damage
          :logfmt      :fall-damage
          :event       :other-damage
          :line        "5/25 23:10:40.994  You fall and lose 939 health."
          :timestamp   (parse-log-timestamp "5/25 23:10:40.994" options)
          :target-name owner-char-name
          :source      "Falling"
          :damage      939})))
