(ns vwowrla.core.matchers.skill-heals-target-test
  (:import
    (java.util TimeZone))
  (:use
    clojure.test
    vwowrla.core.matchers.matchers-test-utils)
  (:require
    [vwowrla.core.parser :refer [parse-line]]
    [vwowrla.core.preparsing :refer [parse-log-timestamp]]
    [vwowrla.core.matchers :refer [regex-matchers]]))

(def options {:log-owner-char-name "Blasticus"
              :year                2015
              :timezone            (TimeZone/getDefault)
              :windows?            false})

(def owner-char-name (:log-owner-char-name options))
(def year (:year options))
(def timezone (:timezone options))

(deftest skill-heals-target-self
  (is (valid-matcher? (get-matcher regex-matchers :skill-heals-target-self)))

  (is (= (parse-line "6/9 22:16:35.330  Your Healing Potion heals you for 1627." options)
         {:id          :skill-heals-target-self
          :logfmt      :skill-heals-target
          :event       :skill-heals-target
          :line        "6/9 22:16:35.330  Your Healing Potion heals you for 1627."
          :timestamp   (parse-log-timestamp "6/9 22:16:35.330" options)
          :target-name owner-char-name
          :source-name owner-char-name
          :skill       "Healing Potion"
          :amount      1627
          :crit?       false}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  Your Healing Touch critically heals you for 3000." options)
         {:id          :skill-heals-target-self
          :logfmt      :skill-heals-target
          :event       :skill-heals-target
          :line        "1/2 3:45:00.123  Your Healing Touch critically heals you for 3000."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name owner-char-name
          :source-name owner-char-name
          :skill       "Healing Touch"
          :amount      3000
          :crit?       true})))

(deftest skill-heals-target
  (is (valid-matcher? (get-matcher regex-matchers :skill-heals-target)))

  (is (= (parse-line "5/25 21:16:40.096  Fei's Lesser Healing Wave heals Futilian for 1012." options)
         {:id          :skill-heals-target
          :logfmt      :skill-heals-target
          :event       :skill-heals-target
          :line        "5/25 21:16:40.096  Fei's Lesser Healing Wave heals Futilian for 1012."
          :timestamp   (parse-log-timestamp "5/25 21:16:40.096" options)
          :target-name "Futilian"
          :source-name "Fei"
          :skill       "Lesser Healing Wave"
          :amount      1012
          :crit?       false}))

  (is (= (parse-line "5/25 21:16:40.686  Leaf's Regrowth critically heals Futilian for 1885." options)
         {:id          :skill-heals-target
          :logfmt      :skill-heals-target
          :event       :skill-heals-target
          :line        "5/25 21:16:40.686  Leaf's Regrowth critically heals Futilian for 1885."
          :timestamp   (parse-log-timestamp "5/25 21:16:40.686" options)
          :target-name "Futilian"
          :source-name "Leaf"
          :skill       "Regrowth"
          :amount      1885
          :crit?       true}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  Ribbly's Crony's Unit Tester's Heal heals you for 2000." options)
         {:id          :skill-heals-target
          :logfmt      :skill-heals-target
          :event       :skill-heals-target
          :line        "1/2 3:45:00.123  Ribbly's Crony's Unit Tester's Heal heals you for 2000."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name owner-char-name
          :source-name "Ribbly's Crony"
          :skill       "Unit Tester's Heal"
          :amount      2000
          :crit?       false}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  Ribbly's Crony's Test Heal critically heals Futilian for 3000." options)
         {:id          :skill-heals-target
          :logfmt      :skill-heals-target
          :event       :skill-heals-target
          :line        "1/2 3:45:00.123  Ribbly's Crony's Test Heal critically heals Futilian for 3000."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name "Futilian"
          :source-name "Ribbly's Crony"
          :skill       "Test Heal"
          :amount      3000
          :crit?       true})))
