(ns vwowrla.core.matchers.special-gained-test
  (:import
    (java.util TimeZone))
  (:use
    clojure.test
    vwowrla.core.matchers.matchers-test-utils)
  (:require
    [vwowrla.core.parser :refer [parse-line]]
    [vwowrla.core.preparsing :refer [parse-log-timestamp]]
    [vwowrla.core.matchers :refer [regex-matchers]]))

(def options {:log-owner-char-name "Blasticus"
              :year                2015
              :timezone            (TimeZone/getDefault)
              :windows?            false})

(def owner-char-name (:log-owner-char-name options))
(def year (:year options))
(def timezone (:timezone options))

(deftest special-gained
  (is (valid-matcher? (get-matcher regex-matchers :special-gained)))

  (is (= (parse-line "5/25 21:13:34.098  Futilian gains 2 extra attacks through Fury of Forgewright." options)
         {:id          :special-gained
          :logfmt      :special-gained
          :event       :special-gained
          :line        "5/25 21:13:34.098  Futilian gains 2 extra attacks through Fury of Forgewright."
          :timestamp   (parse-log-timestamp "5/25 21:13:34.098" options)
          :target-name "Futilian"
          :source      "Fury of Forgewright"
          :special     "2 extra attacks"}))

  (is (= (parse-line "5/25 21:16:16.199  Bigjuicy gains 1 extra attack through Hand of Justice." options)
         {:id          :special-gained
          :logfmt      :special-gained
          :event       :special-gained
          :line        "5/25 21:16:16.199  Bigjuicy gains 1 extra attack through Hand of Justice."
          :timestamp   (parse-log-timestamp "5/25 21:16:16.199" options)
          :target-name "Bigjuicy"
          :source      "Hand of Justice"
          :special     "1 extra attack"}))

  ; NOTE: this combat log entry was not generated by the WoW client, it was hand-written for this test
  (is (= (parse-line "1/2 3:45:00.123  You gains 1 extra attack through Sword Specialization." options)
         {:id          :special-gained
          :logfmt      :special-gained
          :event       :special-gained
          :line        "1/2 3:45:00.123  You gains 1 extra attack through Sword Specialization."
          :timestamp   (parse-log-timestamp "1/2 3:45:00.123" options)
          :target-name owner-char-name
          :source      "Sword Specialization"
          :special     "1 extra attack"})))
